route:
  group_by: ['alertname']
  group_interval: 30s
  repeat_interval: 30s
  group_wait: 30s
  receiver: 'prometheus-msteams'

receivers:
- name: 'prometheus-msteams'
  webhook_configs: 
  - send_resolved: true
#    url: 'http://promteam:2000/_dynamicwebhook/convergytics365.webhook.office.com/webhookb2/6883d9e2-fb45-4f88-b255-f63a5ffc4db7@ccee0f6e-bef4-438b-a166-124ab99600c0/IncomingWebhook/866bb5f2f7d34f9c9d3dee45e22f36be/d559bb8c-2c14-4ae0-a75b-6394837937ac'
    url: 'http://promteam:2000/alertmanager' # the prometheus-msteams proxy + "/_dynamicwebhook/" + webhook url (without prefix "https://")
    # new created webhooks have a different format: https://yourtenant.webhook.office.com/webhookb2/xxx...


















#route:
#    receiver: 'slack'

#receivers:
#    - name: 'slack'
#      slack_configs:
#          - send_resolved: true
#            username: 'Prometheus'
#            channel: '#containers'
#            api_url: 'https://hooks.slack.com/services/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'
#            title: |-
#              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} 
#              for {{ .CommonLabels.job }}
#              {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
#                {{" "}}(
#                {{- with .CommonLabels.Remove .GroupLabels.Names }}
#                  {{- range $index, $label := .SortedPairs -}}
#                    {{ if $index }}, {{ end }}
#                    {{- $label.Name }}="{{ $label.Value -}}"
#                  {{- end }}
#                {{- end -}}
#                )
#              {{- end }}
#            text: >-
#              {{ range .Alerts -}}
#              *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
#         
#              *Description:* {{ .Annotations.description }}
#         
#              *Details:*
#                {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
#                {{ end }}
#              {{ end }}
